### ISSUE TITLE
Improve Readability of Vue Template Syntax

### ISSUE THREAD

**Issue by srd4** [srd4/winged#45]
#### Problem:
Some parts of the Vue templates in our codebase are using a concise but less-readable formatting style, especially with multiple attributes and bindings in elements.

#### Example:
Current formatting:
```html
<a v-on:click="$emit('new-active', container)"
   v-bind:class="{ active: activeContainer === container }">
  {{container.name}}</a>
```

#### Proposed Solution:
Improve readability by adopting a more consistent and readable formatting style:

```html
<a v-on:click="$emit('new-active', container)"
   v-bind:class="{ active: activeContainer === container }">
  {{container.name}}
</a>
```

This change aligns the attributes and places the content on a new line, making it easier to scan and understand the structure.

#### Tasks:
- [ ] Identify all instances in the codebase where this formatting can be improved.
- [ ] Update the templates to use the more readable formatting style.
- [ ] Optionally, consider implementing a linter rule to enforce this style in the future.

#### Acceptance Criteria:
- All updated templates should follow the new formatting style.
- The application should continue to function as expected with no regression in behavior.
