### ISSUE TITLE
Migrate TextField to JSONField on ItemVsTwoCriteriaAIComparison's response field.

### ISSUE THREAD

**Issue by srd4** [srd4/winged#65]
### Overview
We have an existing `TextField` in a Django model that stores JSON strings. The goal is to migrate this to a native `JSONField` to better align with its usage and enable more efficient queries.

### Tasks

- [x] **Backup Current Database**
  - Run a complete backup before initiating the migration process.

- [x] **Validate Current Data**
  - Create a script to validate that all entries in the current `TextField` are valid JSON strings.

- [x] **Add JSONField to Model**
  - Add a new `JSONField` to the model.
  ```python
  new_jsonfield = models.JSONField(null=True)
  ```

- [x] **Create Data Migration Script**
  - Create a script to copy data from the `TextField` to the `JSONField`.

- [x] **Run Initial Migrations**
  - Run `python manage.py makemigrations` and `python manage.py migrate`.

- [x] **Test New Field**
  - Verify that data has been correctly copied to the new `JSONField` and that it works as expected.

- [x] **Remove Old TextField**
  - Once data migration is verified, remove the old `TextField` from the model.

- [x] **Run Final Migrations**
  - Run `python manage.py makemigrations` and `python manage.py migrate` to remove the old field.

### Additional Notes
- Make sure to perform these changes in a development environment first.
- Test thoroughly before deploying to production.
